os: linux
dist: bionic
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  # for clang-format 10
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository 'deb http://apt.llvm.org/bionic/   llvm-toolchain-bionic-10 main'
  - sudo apt-get update

install:
  - sudo apt-get install cppcheck
  - sudo apt-get install clang-format-10
  - clang-format-10 --version
  - pwd
  - cd ..
  - git clone https://github.com/nasa/cFS.git

before_script:
  - cp -r ci_lab cFS/apps

script:
# Get bundle (doesn't populate submodules, not needed for style enforcement)
  - cd cFS/apps/ci_lab
#   # Enforce formatting
#   - find . -name "*.[ch]" -exec clang-format-10 -i -style=file {} +
#   - git diff > style_differences.txt
#   - |
#     if [[ -s style_differences.txt ]]; then
#       echo "You must fix style differences before submitting a pull request"
#       echo ""
#       cat style_differences.txt
#       exit -1
#     fi
# script:
#   - git submodule init
#   - cp ci_lab cFS/apps
